[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Perseus Image plug-in Manual"
authors = [{name = "Bela Frohn" "Carlo De Nart, email = "carlo.denart@gmail.com"}]
dynamic = ["0.1", "Hopefully this manual will help"]
